griffithlab/pVAC-Seq

t/GenerateFastaKey.t, t/GenerateVariantSequences.t, t/ParseOutputNetmhc_and_BindingFilter.t
This PR adds tests for the basic steps/scripts that are run as part of `pVAC-Seq.pl`.
This closes #15
=> Basic tests for the pVAC-Seq steps

.gitignore, bin/BindingFilter.pl, bin/CoverageFilters.pl, bin/GenerateFastaForNetChop.pl, bin/GenerateFastaKey.pl, bin/GenerateVariantSequences.pl, bin/ParseOutputNetmhc.pl, pVAC-Seq.pl
I just ran perltidy on the pl files, and let it do its thing.
#16
=> Ran basic perltidy on all the perl scripts

pvacseq/lib/parse_output.py
Ensures consistency of output across identical runs of the program
=> Added lexographic sort to the parse_output sorting

pvacseq/lib/main.py
=> Silenced stdout from NetMHC

README.md, pvacseq/lib/main.py, setup.py
Silence the output from NetMHC
=> Hotfix 2.0.1

pvacseq/iedb_alleles/ann.tsv, pvacseq/iedb_alleles/netmhccons.tsv, pvacseq/iedb_alleles/netmhcpan.tsv, pvacseq/iedb_alleles/pickpocket.tsv, pvacseq/iedb_alleles/smm.tsv, pvacseq/iedb_alleles/smmpmbec.tsv
=> Changed mouse allele names to match IEDB format

pvacseq/lib/main.py
=> Check that the fasta file has size

pvacseq/lib/main.py, pvacseq/lib/parse_output.py
=> Handle '.' in sample names and output directories

pvacseq/lib/main.py
=> Handle relative output directory paths correctly

pvacseq/lib/main.py
This PR address the bug in issue #133.
=> Don't run parse and combine if there are no input files

pvacseq/lib/main.py, pvacseq/pvacseq.py
This will make the order of commands/arguments more intuitive for the users during display of the help text.
=> Reorder subcommands and arguments

pvacseq/lib/generate_fasta.py, pvacseq/lib/parse_output.py
This addresses the issue in #158.
=> Increase csv.field_size_limit

.travis.yml, pvacseq/lib/__init__.py, pvacseq/lib/config_files.py, pvacseq/lib/main.py, pvacseq/pvacseq.py, setup.py, tests/test_config_files.py, tests/test_data/pvacseq/additional_input_file_list.yaml, tests/test_pvacseq.py
This is in preparation for bam-readcount input files.
=> Use a yaml file to list additional input files instead of individual params

setup.py
Users can now install from the develop branch with the following command:
`pip install git+git://github.com/griffithlab/pVAC-Seq.git@develop#egg=pvacseq`
=> Reworked package_data to allow development installs

pvacseq/lib/generate_fasta.py, pvacseq/lib/pipeline.py, tests/test_data/generate_fasta/input_X_sequence.tsv, tests/test_data/generate_fasta/input_short_fasta_sequence.tsv, tests/test_generate_fasta.py
=> Filter fasta sequences to prevent downstream errors

pvacseq/pvacseq.py, tests/test_pvacseq.py
=> Remove certain subcommands for individual steps

pvacseq/lib/convert_vcf.py
This will fix an error where a position doesn't have a bam_readcount entry.
Closes #207
=> Check all keys in nested dict  before accessing element

pvacseq/lib/pipeline.py
=> Don't reprocess TSV if it already exists

pvacseq/lib/call_iedb.py, pvacseq/lib/main.py, pvacseq/lib/pipeline.py, pvacseq/server/controllers/default_controller.py, pvacseq/server/swagger/swagger.yaml, pvacseq/server/test_start.html
=> Add a iedb_retries parameter to controll how many calls to IEDB are made

tests/test_data/pvacseq/additional_input_file_list.yaml, tests/test_pvacseq.py
Closes #216.
This will allow us to execute this test from any directory.
=> Create the additional_input_file_list.yaml in code

pvacseq/lib/convert_vcf.py, tests/test_convert_vcf.py, tests/test_data/convert_vcf/input_hom_ref_genotype.vcf, tests/test_data/convert_vcf/input_uncalled_genotype.vcf, tests/test_data/convert_vcf/output_hom_ref_genotype.tsv, tests/test_data/convert_vcf/output_uncalled_genotype.tsv
=> Skip variants that are hom_ref or uncalled

pvacseq/lib/convert_vcf.py
=> Only check the sample genotype if the VCF contains a sample

pvacseq/lib/parse_output.py
This is a fix to our best guess as to what is causing the error in #239. Unfortunately, I haven't been able to reproduce this error and without test data I don't know if this will really fix this error.
=> Attempt to handle mysterious str comparison error

pvacseq/lib/call_iedb.py
=> Check run return code from local IEDB install before proceeding

pvacseq/lib/prediction_class.py, tests/test_call_iedb.py, tests/test_pvacseq.py
=> Update IEDB RESTful-API URL

.travis.yml, pvacseq/lib/call_iedb.py, pvacseq/lib/pipeline.py, tests/test_pvacseq.py
Unfortunately, this change also affects the pvacseq.py test. Ideas on how to circumvent this are very welcome.
=> Wait 60 seconds between requests to the IEDB API

pvacseq/lib/call_iedb.py, tests/test_call_iedb.py
=> respone_text from IEDB is byte not str - handle accordingly

pvacseq/lib/binding_filter.py
This addresses the error in issue #306.
=> Remove unnecessary line of code

pvacseq/server/app.py, pvacseq/server/config/swagger.yaml, pvacseq/server/controllers/files.py, pvacseq/server/controllers/staging.py, tests/test_api.py
valid_alleles and prediction_algorithm functions added to staging.py
swagger file updated to include new endpoints
fixed module import issue in app.py to allow 'python app.py' command to work
filter out invisible files from /input endpoint
=> Add new endpoints & update tests and swagger

pvacseq/lib/generate_fasta.py
=> Die if the wildtype amino acid in the wildtype sequence is different from the one in the amino acid change
